Code test website and script/website working-ish v13/myproject/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
import json


class Drc_error(models.Model):
    error_names = models.TextField(default = "[]")

    def get_error_names(self):
        return json.loads(self.error_names)

    def set_error_names(self, error_names):
        self.error_names = json.dumps(error_names)

    errors_names = property(get_error_names, set_error_names)


class UploadedFile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to='uploads/')
    description = models.TextField(default='')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    filename = models.TextField(max_length=100, default='')

class ResultFile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    uploaded_file = models.ForeignKey(UploadedFile, on_delete=models.CASCADE, default=None)
    zippedGerbers = models.FileField(upload_to='uploads/')
    zippedDrills = models.FileField(upload_to='uploads/')
    DRCresult = models.FileField(upload_to='uploads/')
    ERCresult = models.FileField(upload_to='uploads/')
    pdf_file = models.FileField(upload_to='uploads/', default='uploads/test.pdf')
    description = models.TextField(max_length=100, default='')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    filename = models.TextField(max_length=100, default='')
    valid = models.BooleanField(default=False)
    version = models.IntegerField(default=1)
    locked = models.BooleanField(default=False)
    Errors = models.OneToOneField(Drc_error, on_delete=models.CASCADE)

    def __str__(self):
        return self.filename


class AuthorizedError(models.Model):
    error_names = models.TextField(unique=True)

    def get_error_names(self):
        return json.loads(self.error_names)

    def set_error_names(self, error_names):
        self.error_names = json.dumps(error_names)

    authorized_error_names = property(get_error_names, set_error_names)


class ModelList(models.Model):
    error_names = models.TextField(unique=True)

    def get_values(self):
        return json.loads(self.error_names)

    def set_values(self, error_names):
        self.error_names = json.dumps(error_names)

    values = property(get_values, set_values)

class PanelFile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    filename = models.TextField(max_length=100, default='') 
    description = models.TextField(default='')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    result_files = models.ManyToManyField(ResultFile)
    amounts = models.OneToOneField(ModelList, on_delete=models.CASCADE, default=0)
    panel_file = models.FileField(upload_to='Panels/')
    zippedGerbers = models.FileField(upload_to='uploads/', default='zzccmxtp.zip')
    zippedDrills = models.FileField(upload_to='uploads/', default='zzccmxtp.zip')    
    kicad_pcb = models.FileField(upload_to='uploads/', default='zzccmxtp.zip')   
    Errors = models.OneToOneField(Drc_error, on_delete=models.CASCADE)
     
    def __str__(self):
        return self.filename
    
class Ticket(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    resolved = models.BooleanField(default=False)
    staff_response = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    co_users = models.ManyToManyField(User, related_name='co_tickets', blank=True)
    reopened = models.BooleanField(default=False)
    reopen_requested = models.BooleanField(default=False)
    result_file = models.OneToOneField(ResultFile, on_delete=models.CASCADE, blank=True, null=True, default=None)
    panel_file = models.OneToOneField(PanelFile, on_delete=models.CASCADE, blank=True, null=True, default=None)

    def __str__(self):
        return self.title
    
class Message(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    answeredByStaff = models.BooleanField(default=False)

    def __str__(self):
        return self.content

Code test website and script/website working-ish v13/myproject/myapp/templates/panel_edit.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Edit Panel File</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/panel_edit.css' %}">
  {% include 'header.html' %}
</head>
<body>
  <div class="panel-file-details">
    <h1 class="form-heading">Edit Panel File</h1>
    <div class="form-field">
      <label>User:</label>
      <span>{{ panel_file.user }}</span>
    </div>
    <div class="form-field">
      <label>Kicad pcb from Panel:</label>
      {% if panel_file.kicad_pcb %}
        <a href="{% url 'view_file' file_id=panel_file.id file_type='kicad_pcb_file_panel' %}" target="_blank" class="file-link">{{ panel_file.kicad_pcb.name }}</a>
      {% else %}
        <span class="no-file">No file uploaded</span>
      {% endif %}
    </div>
    <div class="form-field">
      <label>ID:</label>
      <span>{{ panel_file.id }}</span>
    </div>
    <div class="form-field">
      <label>Description:</label>
      <span>{{ panel_file.description }}</span>
    </div>
  </div>
  <div class="form-container">
    <h2 class="form-heading">Upload New File</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="form-field">
        <label for="id_result_files">Panel name:</label>
        {{ form.filename }}
      </div>
      <div class="form-field">
        <label for="id_result_files">Result Files:</label>
        {{ form.result_files }}
      </div>
      <div class="form-field">
        <label for="id_description">Description:</label>
        {{ form.description }}
      </div>
      <button type="submit" class="btn-submit">Upload</button>
    </form>
  </div>
</body>
</html>

Code test website and script/website working-ish v13/myproject/myapp/templates/panelizer_kicad.html
{% load static %}
{% include 'header.html' %}

<!DOCTYPE html>
<html>
<head>
  <title>User Files</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/panelizer_kicad.css' %}">
</head>
<body>



<h1>Project Available for Panelizing</h1>

<form action="{% url 'run_script' %}" method="post">
    {% csrf_token %}
    {% if resultfiles%}
    <ul class="file-list">
      {% for file in resultfiles  %}
        {% if file.valid %}
          <li class="file-item">
        {% else %}
          <li class="file-item-not-valid">         
        {% endif %}
        
          <div class="file-details">
            {% if file.valid %}
              <p class="file-name-valid">{{ file.filename}}, this file is valid : {{ file.valid}}</p>
              <p class="file-description">{{ file.description }}</p>
              <p class="file-date">{{ file.uploaded_at }}</p>
            {% else %}
              <p class="file-name-not-valid">{{ file.filename}}, this file is valid : {{ file.valid}}</p>
              <p class="file-description">{{ file.description }}</p>
              <p class="file-date">{{ file.uploaded_at }}</p>            
            {% endif %}
          </div>
          <a href="{% url 'view_file' file_id=file.id file_type='zippedGerbers' %}" class="file-button">View zipped Gerbers</a>
          <a href="{% url 'view_file' file_id=file.id file_type='zippedDrills' %}" class="file-button">View zipped Drills</a>
          <a href="{% url 'view_file' file_id=file.id file_type='DRCresult' %}" class="file-button">View DRC Result</a>
          <a href="{% url 'view_file' file_id=file.id file_type='ERCresult' %}" class="file-button">View ERC Result</a>
          <a href="{% url 'view_file' file_id=file.id file_type='uploaded_file' %}" class="file-button">View Kicad Project</a>
          {% if user.is_staff%}
          <label class="checkbox-label">
            <input type="checkbox" class="file-checkbox" name="selected_files" value="{{ file.id }}">
            <span class="checkbox-text">Unselected</span>
          </label>
          {% endif%}

          
          <!-- Update the amount-selector section in your HTML -->
          <div class="amount-selector">
            <label for="amount_{{ file.id }}" class="amount-label">Amount:</label>
            <input type="number" id="amount_{{ file.id }}" class="amount-input" name="amount_{{ file.id }}" value="1" min="1">
          </div>
          



          <button class="delete-button" data-file-type="result_file" data-file-id="{{ file.id }}">Delete</button>
        </li>
      {% empty %}
        <li>No files uploaded yet.</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No files uploaded yet.</p>
  {% endif %}

  {% if user.is_staff %}
  <div class="panel-section">
      <label for="board_height" class="panel-info">Panel Height (in mm):</label>
      <input type="number" id="board_height" name="board_height" required minlength="1" size="16" placeholder="Often from 200 to 1000" class="panel-input">
      
      <label for="board_width" class="panel-info">Panel Width (in mm):</label>
      <input type="number" id="board_width" name="board_width" required minlength="1" size="16" placeholder="Often from 200 to 1000" class="panel-input">
      
      <label for="spacing" class="panel-info">Spacing (in mm):</label>
      <input type="number" id="spacing" name="spacing" required minlength="1" size="16" placeholder="Often from 0.2 to 5 mm" class="panel-input">
      
      <label for="fit_mode" class="panel-info">Fit Mode for the PCBs :</label>
        <select id="fit_mode" name="fit_mode" required class="panel-input">
          <option value="">Select a Fit Mode</option>
          <option value="Polygons">Polygons (Slow)</option>
          <option value="Rectangles">Rectangles (Fast)</option>
          <option value="EasyCut">Easy Straight line Cutting (Fast)</option>
        </select>
        <p class="panel-subinfo">Slow : Expect 10 min</p>
        <p class="panel-subinfo">Fast : Expect 1 min</p>


      <button type="submit" class="panel-button">Run Panelizer with Selected File</button>
  </div>
  {% endif %}
</form>



<!-- JavaScript code -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $('.delete-button').click(function() {
      var fileId = $(this).data('file-id');
      var fileType = $(this).data('file-type');
      if (confirm('Are you sure you want to delete this file?')) {
        $.ajax({
          type: 'POST',
          url: '{% url 'delete_file' %}',
          data: { file_id: fileId, file_type: fileType, csrfmiddlewaretoken: '{{ csrf_token }}' },
          success: function(response) {
            // Handle success response
            console.log(response);
            // Refresh the page or update the file list dynamically
            location.reload();
          },
          error: function(xhr, errmsg, err) {
            // Handle error response
            console.log(xhr.status + ': ' + xhr.responseText);
          }
        });
      }
    });
  });
</script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    $('.file-checkbox').change(function() {
      var checkbox = $(this);
      var checkboxText = checkbox.siblings('.checkbox-text');
      
      if (checkbox.is(':checked')) {
        checkboxText.text('Selected');
        checkbox.parent().addClass('selected').removeClass('not-selected');
      } else {
        checkboxText.text('Unselected');
        checkbox.parent().addClass('not-selected').removeClass('selected');
      }
    });
  });
</script>



</body>
</html>

Code test website and script/website working-ish v13/myproject/myapp/templates/user_files.html
{% load static %}
{% include 'header.html' %}

<!DOCTYPE html>
<html>
<head>
  <title>User Files</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/user_files.css' %}">
  
</head>
<body>

<div class="form-container">
  {% if user.is_staff %}
  <form method="POST" action="{% url 'user_files' %}">
    {% csrf_token %}
    <label for="view_all_project">View All Projects</label>
    <input type="checkbox" id="view_all_project" name="view_all_project" {% if view_all_project %}checked="checked"{% endif %}>
    <input type="hidden" name="view_valid" value="{{ view_valid }}">
    <button type="submit">Apply</button>
  </form>
  {% endif %}

  <form method="POST" action="{% url 'user_files' %}">
    {% csrf_token %}
    <label for="view_valid">View Valid</label>
    <input type="checkbox" id="view_valid" name="view_valid" {% if view_valid %}checked="checked"{% endif %}>
    <input type="hidden" name="view_all_project" value="{{ view_all_project }}">
    <button type="submit">Apply</button>
  </form>
</div>



{% if user.is_staff %}
<h1>List of the Projets</h1>
{% else %}
<h1>List of your Projets</h1>
{% endif %}

{% csrf_token %}
{% if files%}
<ul class="file-list">
  {% for file in files  %}
    <li class="file-item">
      <div class="file-details">
        <p class="file-name">{{ file.upload_file.filename}}</p>
        <p class="file-description">{{ file.upload_file.description }}</p>
        <p class="file-date">{{ file.upload_file.uploaded_at }}</p>
      </div>
      <div class="file-details">
        <a class="file-valid">Is File Valid : {{ file.upload_file.valid }}</a>
      </div>

      {% if file.upload_file.valid %}
      <a href="{% url 'view_file' file_id=file.upload_file.id file_type='zippedGerbers' %}" class="file-button">View zipped Gerbers</a>
      <a href="{% url 'view_file' file_id=file.upload_file.id file_type='zippedDrills' %}" class="file-button">View zipped Drills</a>
      {% endif %}
      <a href="{% url 'view_file' file_id=file.upload_file.id file_type='DRCresult' %}" class="file-button">View DRC Result</a>
      <a href="{% url 'view_file' file_id=file.upload_file.id file_type='ERCresult' %}" class="file-button">View ERC Result</a>
      <a href="{% url 'view_file' file_id=file.upload_file.id file_type='uploaded_file' %}" class="file-button">View Kicad Project</a>
      
      
      {% if file.ticket %}
      <a href="{% url 'gerber_edit' file_id=file.upload_file.id ticket_id=file.ticket.id%}" class="file-button">Edit Project</a>
        <a href="{% url 'open_ticket' file_id=file.upload_file.id %}"class="file-button">Open Ticket</a>
      {% else %}
      <a href="{% url 'gerber_edit' file_id=file.upload_file.id%}" class="file-button">Edit Project</a>
        <a href="{% url 'ticket_create' file_id=file.upload_file.id %}"class="file-button">Create Ticket</a>
      {% endif %}

      <button class="delete-button" data-file-type="result_file" data-file-id="{{ file.upload_file.id }}">Delete</button>
    </li>
  {% empty %}
    <li>No files uploaded yet.</li>
  {% endfor %}
</ul>
{% else %}
<p>No files uploaded yet.</p>
{% endif %}



<!-- JavaScript code -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $('.delete-button').click(function() {
      var fileId = $(this).data('file-id');
      var fileType = $(this).data('file-type');
      if (confirm('Are you sure you want to delete this file?')) {
        $.ajax({
          type: 'POST',
          url: '{% url 'delete_file' %}',
          data: { file_id: fileId, file_type: fileType, csrfmiddlewaretoken: '{{ csrf_token }}' },
          success: function(response) {
            // Handle success response
            console.log(response);
            // Refresh the page or update the file list dynamically
            location.reload();
          },
          error: function(xhr, errmsg, err) {
            // Handle error response
            console.log(xhr.status + ': ' + xhr.responseText);
          }
        });
      }
    });
  });
</script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    $('.file-checkbox').change(function() {
      var checkbox = $(this);
      var checkboxText = checkbox.siblings('.checkbox-text');
      
      if (checkbox.is(':checked')) {
        checkboxText.text('Selected');
        checkbox.parent().addClass('selected').removeClass('not-selected');
      } else {
        checkboxText.text('Unselected');
        checkbox.parent().addClass('not-selected').removeClass('selected');
      }
    });
  });
</script>



</body>
</html>